import Head from "next/head";
import ObjectTable from "@/components/table/ObjectTable";
import { objectColumns } from "@/components/table/utils";
import Link from "next/link";
import useHubspot from "@/hooks/useHubspot";
import { useEffect, useState } from "react";

export default function Home() {
	const { checkAuthStatus } = useHubspot();

	const [isHubspotConnected, setIsHubspotConnected] = useState(false);

	useEffect(() => {
		(async () => {
			try {
				const response = await checkAuthStatus();
				setIsHubspotConnected(response);
			} catch (e) {
				throw new Error(`API error:${e}`);
			}
		})();
	}, [checkAuthStatus]);

	return (
		<>
			<Head>
				<title>Hubspot Data Viewer</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-col space-y-4 p-4 min-h-screen">
				<div className="w-full flex flex-row justify-between">
					<h1 className="text-3xl font-bold">Hubspot Data Viewer</h1>
					<div className="bg-transparent hover:bg-grey-500 text-grey-700 font-semibold py-2 px-4 border border-black-500 rounded">
						<Link href="/oauth">Connect to Hubspot</Link>
					</div>
				</div>
				{isHubspotConnected ? (
					<>
						<ObjectTable
							object="companies"
							headers={objectColumns.companies}
						/>
						<ObjectTable
							object="contacts"
							headers={objectColumns.contacts}
						/>
						<ObjectTable
							object="deals"
							headers={objectColumns.deals}
						/>
					</>
				) : (
					<p>Please connect your Hubspot account to proceed.</p>
				)}
			</main>
		</>
	);
}
